# This is the main configuration file for the application.
# See https://github.com/playframework/play1/blob/master/documentation/manual/configuration.textile for all possible values
#
# Make a copy of this file and rename to application.conf, do not include it in git.
# Fill out the missing values and remove DEV or PRODUCTION section based in context.

# GENERAL
application.name=grundtvigsværker.dk
date.format=yyyy-MM-dd
jvm.memory=-Xmx2g
attachments.path=data/attachments
mail.smtp=mock

data.dir=

# DEV (remove PRODUCTION)
application.mode=dev
application.secret=testtesttest

db=fs

solr.url=http://localhost:8983/solr/gv

play.baseurl=http://localhost:9000
# DEV END


# PRODUCTION (remove DEV)
application.mode=prod
application.secret=CHANGE_THIS

db.url=jdbc:postgresql://localhost:5432/gvigdb
db.driver=org.postgresql.Driver
db.user=gvig
db.pass=CHANGE_THIS
jpa.ddl=none

solr.url=http://localhost:8983/solr/gv
play.baseurl=https://grundtvigsværker.dk
# PRODUCTION END

